"""empty message

Revision ID: 691ab4a8d8c6
Revises: 
Create Date: 2022-06-28 00:16:33.734115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691ab4a8d8c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('one')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('one',
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
